site_name: Music Notes
repo_url: https://github.com/Alysson93/music-notes
repo_name: Alysson93/music-notes
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png


markdown_extensions:
  - attr_list
  - admonition

extra_css:
  - stylesheets/extra.css

watch:
  - music_notes

plugins:
- macros
- mkdocstrings:
    handlers:
      python:
        paths: [music_notes]


extra:
  commands:
    run: poetry run music-notes